### ISSUE TITLE
Null is not an object evaluating e.getBoundingClientRect

### ISSUE THREAD

**Issue by luisherranz** [frontity/lazyload#12]
We are getting some of these in Safari:
https://rollbar.com/worona/pwa/items/6031/

`element` is null when `fastdom` tries to evaluate it:
https://github.com/frontity/lazyload/blob/master/src/utils/fastdom.js#L7

Maybe it happens because `fastdom` is async and sometimes when the user triggers a lazy load but then changes the screen before the rAF of `fastdom` is resolved the element is not there anymore.

**Comment by luisherranz** [comment]
@darerodz quick question: could we substitute this implementation with one based on the intersection observer?

If so, maybe it doesn't make much sense to fix this.

**Comment by DAreRodz** [comment]
Yes, we could do that. I added a quick fix and some refactor for now.

**Comment by luisherranz** [comment]
Aproved the PR of `lazyload`. You can now release new version and upgrade it on `frontity`.
